package org.kodluyoruz.mybank.transaction;

public enum TransactionType {
    TRANSFER,WITHDRAWAL_ACCOUNT,WITHDRAWAL_DEBITCARD,DEPOSIT_ACCOUNT,DEPOSIT_DEBITCARD,SHOPPING_DEBITCARD,
    SHOPPING_CREDITCARD,SHOPPING_ACCOUNT,PAYDEBT_ACCOUNT,PAYDEBT_CREDITCARD
}
